// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"
)

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.YoutubeChannelID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.Avatar,
		&i.Banner,
		&i.SubscriberCount,
		&i.UploadsPlaylistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByYouTubeID = `-- name: GetChannelByYouTubeID :one
SELECT id, youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id, created_at, updated_at FROM channels WHERE youtube_channel_id = $1
`

func (q *Queries) GetChannelByYouTubeID(ctx context.Context, youtubeChannelID string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByYouTubeID, youtubeChannelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.YoutubeChannelID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.Avatar,
		&i.Banner,
		&i.SubscriberCount,
		&i.UploadsPlaylistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelIDsBySubscriptionIDs = `-- name: GetChannelIDsBySubscriptionIDs :many
SELECT channel_id FROM subscriptions WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetChannelIDsBySubscriptionIDs(ctx context.Context, dollar_1 []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getChannelIDsBySubscriptionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var channel_id int64
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByIDs = `-- name: ListChannelsByIDs :many
SELECT id, youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id, created_at, updated_at FROM channels WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListChannelsByIDs(ctx context.Context, dollar_1 []int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeChannelID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.Avatar,
			&i.Banner,
			&i.SubscriberCount,
			&i.UploadsPlaylistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChannels = `-- name: SearchChannels :many
SELECT id, youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id, created_at, updated_at FROM channels
WHERE to_tsvector('simple', name || ' ' || COALESCE(handle, '')) @@ plainto_tsquery('simple', $1)
   OR name ILIKE '%' || $1 || '%'
   OR handle ILIKE '%' || $1 || '%'
ORDER BY subscriber_count DESC
LIMIT $2 OFFSET $3
`

type SearchChannelsParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchChannels(ctx context.Context, arg SearchChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, searchChannels, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeChannelID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.Avatar,
			&i.Banner,
			&i.SubscriberCount,
			&i.UploadsPlaylistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (youtube_channel_id) DO UPDATE SET
    name = EXCLUDED.name,
    handle = EXCLUDED.handle,
    description = EXCLUDED.description,
    avatar = EXCLUDED.avatar,
    banner = EXCLUDED.banner,
    subscriber_count = EXCLUDED.subscriber_count,
    uploads_playlist_id = EXCLUDED.uploads_playlist_id,
    updated_at = NOW()
RETURNING id, youtube_channel_id, name, handle, description, avatar, banner, subscriber_count, uploads_playlist_id, created_at, updated_at
`

type UpsertChannelParams struct {
	YoutubeChannelID  string `json:"youtube_channel_id"`
	Name              string `json:"name"`
	Handle            string `json:"handle"`
	Description       string `json:"description"`
	Avatar            string `json:"avatar"`
	Banner            string `json:"banner"`
	SubscriberCount   int64  `json:"subscriber_count"`
	UploadsPlaylistID string `json:"uploads_playlist_id"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.YoutubeChannelID,
		arg.Name,
		arg.Handle,
		arg.Description,
		arg.Avatar,
		arg.Banner,
		arg.SubscriberCount,
		arg.UploadsPlaylistID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.YoutubeChannelID,
		&i.Name,
		&i.Handle,
		&i.Description,
		&i.Avatar,
		&i.Banner,
		&i.SubscriberCount,
		&i.UploadsPlaylistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
