// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelToCollection = `-- name: AddChannelToCollection :exec
INSERT INTO collection_channels (collection_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelToCollectionParams struct {
	CollectionID int64 `json:"collection_id"`
	ChannelID    int64 `json:"channel_id"`
}

func (q *Queries) AddChannelToCollection(ctx context.Context, arg AddChannelToCollectionParams) error {
	_, err := q.db.Exec(ctx, addChannelToCollection, arg.CollectionID, arg.ChannelID)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, name, icon, color)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, icon, color, created_at, updated_at
`

type CreateCollectionParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Icon   string `json:"icon"`
	Color  string `json:"color"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1 AND user_id = $2
`

type DeleteCollectionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.UserID)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, user_id, name, icon, color, created_at, updated_at FROM collections WHERE id = $1 AND user_id = $2
`

type GetCollectionByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionChannels = `-- name: ListCollectionChannels :many
SELECT c.id, c.youtube_channel_id, c.name, c.handle, c.description, c.avatar, c.banner, c.subscriber_count, c.uploads_playlist_id, c.created_at, c.updated_at FROM channels c
JOIN collection_channels cc ON cc.channel_id = c.id
WHERE cc.collection_id = $1
ORDER BY c.name ASC
`

func (q *Queries) ListCollectionChannels(ctx context.Context, collectionID int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listCollectionChannels, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeChannelID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.Avatar,
			&i.Banner,
			&i.SubscriberCount,
			&i.UploadsPlaylistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByChannel = `-- name: ListCollectionsByChannel :many
SELECT cl.id, cl.user_id, cl.name, cl.icon, cl.color, cl.created_at, cl.updated_at FROM collections cl
JOIN collection_channels cc ON cc.collection_id = cl.id
WHERE cc.channel_id = $1 AND cl.user_id = $2
ORDER BY cl.name ASC
`

type ListCollectionsByChannelParams struct {
	ChannelID int64 `json:"channel_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListCollectionsByChannel(ctx context.Context, arg ListCollectionsByChannelParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByChannel, arg.ChannelID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByUser = `-- name: ListCollectionsByUser :many
SELECT id, user_id, name, icon, color, created_at, updated_at FROM collections WHERE user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListCollectionsByUser(ctx context.Context, userID int64) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelFromCollection = `-- name: RemoveChannelFromCollection :exec
DELETE FROM collection_channels WHERE collection_id = $1 AND channel_id = $2
`

type RemoveChannelFromCollectionParams struct {
	CollectionID int64 `json:"collection_id"`
	ChannelID    int64 `json:"channel_id"`
}

func (q *Queries) RemoveChannelFromCollection(ctx context.Context, arg RemoveChannelFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeChannelFromCollection, arg.CollectionID, arg.ChannelID)
	return err
}

const searchCollectionsByUser = `-- name: SearchCollectionsByUser :many
SELECT id, user_id, name, icon, color, created_at, updated_at FROM collections
WHERE user_id = $1 AND name ILIKE '%' || $2 || '%'
ORDER BY name ASC
`

type SearchCollectionsByUserParams struct {
	UserID  int64       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchCollectionsByUser(ctx context.Context, arg SearchCollectionsByUserParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, searchCollectionsByUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $3, icon = $4, color = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, icon, color, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Icon   string `json:"icon"`
	Color  string `json:"color"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
