// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID                int64              `json:"id"`
	YoutubeChannelID  string             `json:"youtube_channel_id"`
	Name              string             `json:"name"`
	Handle            string             `json:"handle"`
	Description       string             `json:"description"`
	Avatar            string             `json:"avatar"`
	Banner            string             `json:"banner"`
	SubscriberCount   int64              `json:"subscriber_count"`
	UploadsPlaylistID string             `json:"uploads_playlist_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Collection struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Icon      string             `json:"icon"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CollectionChannel struct {
	CollectionID int64 `json:"collection_id"`
	ChannelID    int64 `json:"channel_id"`
}

type Note struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	ChannelID int64              `json:"channel_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Rating struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	ChannelID int64              `json:"channel_id"`
	Rating    int16              `json:"rating"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	Data      []byte             `json:"data"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	ChannelID    int64              `json:"channel_id"`
	SubscribedAt pgtype.Timestamptz `json:"subscribed_at"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

type SyncJob struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Status     string             `json:"status"`
	Error      string             `json:"error"`
}

type User struct {
	ID        int64              `json:"id"`
	GoogleID  string             `json:"google_id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	AvatarUrl string             `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID             int64              `json:"id"`
	YoutubeVideoID string             `json:"youtube_video_id"`
	ChannelID      int64              `json:"channel_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Thumbnail      string             `json:"thumbnail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
