// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE user_id = $1 AND channel_id = $2
`

type DeleteNoteParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.UserID, arg.ChannelID)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, channel_id, body, created_at, updated_at FROM notes WHERE user_id = $1 AND channel_id = $2
`

type GetNoteParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.UserID, arg.ChannelID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchNotes = `-- name: SearchNotes :many
SELECT n.id, n.user_id, n.channel_id, n.body, n.created_at, n.updated_at, c.name as channel_name, c.youtube_channel_id, c.avatar as channel_avatar
FROM notes n
JOIN channels c ON c.id = n.channel_id
WHERE n.user_id = $1 AND n.body ILIKE '%' || $2 || '%'
ORDER BY n.updated_at DESC
`

type SearchNotesParams struct {
	UserID  int64       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type SearchNotesRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	ChannelID        int64              `json:"channel_id"`
	Body             string             `json:"body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ChannelName      string             `json:"channel_name"`
	YoutubeChannelID string             `json:"youtube_channel_id"`
	ChannelAvatar    string             `json:"channel_avatar"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error) {
	rows, err := q.db.Query(ctx, searchNotes, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNotesRow{}
	for rows.Next() {
		var i SearchNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelName,
			&i.YoutubeChannelID,
			&i.ChannelAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNote = `-- name: UpsertNote :one
INSERT INTO notes (user_id, channel_id, body)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel_id) DO UPDATE SET
    body = EXCLUDED.body,
    updated_at = NOW()
RETURNING id, user_id, channel_id, body, created_at, updated_at
`

type UpsertNoteParams struct {
	UserID    int64  `json:"user_id"`
	ChannelID int64  `json:"channel_id"`
	Body      string `json:"body"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, upsertNote, arg.UserID, arg.ChannelID, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
