// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddChannelToCollection(ctx context.Context, arg AddChannelToCollectionParams) error
	CountSubscriptionsByUser(ctx context.Context, userID int64) (int64, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSyncJob(ctx context.Context, userID int64) (SyncJob, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteRating(ctx context.Context, arg DeleteRatingParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetAverageRatingForChannel(ctx context.Context, channelID int64) (GetAverageRatingForChannelRow, error)
	GetChannelByID(ctx context.Context, id int64) (Channel, error)
	GetChannelByYouTubeID(ctx context.Context, youtubeChannelID string) (Channel, error)
	GetChannelIDsBySubscriptionIDs(ctx context.Context, dollar_1 []int64) ([]int64, error)
	GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (Collection, error)
	GetLatestSyncJob(ctx context.Context, userID int64) (SyncJob, error)
	GetLatestVideoByChannelID(ctx context.Context, channelID int64) (Video, error)
	GetNote(ctx context.Context, arg GetNoteParams) (Note, error)
	GetRating(ctx context.Context, arg GetRatingParams) (Rating, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionByUserID(ctx context.Context, userID int64) (Session, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetVideoByYouTubeID(ctx context.Context, youtubeVideoID string) (Video, error)
	GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error)
	ListChannelsByIDs(ctx context.Context, dollar_1 []int64) ([]Channel, error)
	ListCollectionChannels(ctx context.Context, collectionID int64) ([]Channel, error)
	ListCollectionsByChannel(ctx context.Context, arg ListCollectionsByChannelParams) ([]Collection, error)
	ListCollectionsByUser(ctx context.Context, userID int64) ([]Collection, error)
	ListSubscriptionChannelsByUser(ctx context.Context, userID int64) ([]Channel, error)
	ListSubscriptionsByName(ctx context.Context, arg ListSubscriptionsByNameParams) ([]ListSubscriptionsByNameRow, error)
	ListSubscriptionsByRecent(ctx context.Context, arg ListSubscriptionsByRecentParams) ([]ListSubscriptionsByRecentRow, error)
	ListSyncJobsByUser(ctx context.Context, arg ListSyncJobsByUserParams) ([]SyncJob, error)
	ListVideosByChannelID(ctx context.Context, arg ListVideosByChannelIDParams) ([]Video, error)
	RemoveChannelFromCollection(ctx context.Context, arg RemoveChannelFromCollectionParams) error
	SearchChannels(ctx context.Context, arg SearchChannelsParams) ([]Channel, error)
	SearchCollectionsByUser(ctx context.Context, arg SearchCollectionsByUserParams) ([]Collection, error)
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateSyncJobStatus(ctx context.Context, arg UpdateSyncJobStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error)
	UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UpsertVideo(ctx context.Context, arg UpsertVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
