// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlc

import (
	"context"
)

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings WHERE user_id = $1 AND channel_id = $2
`

type DeleteRatingParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.Exec(ctx, deleteRating, arg.UserID, arg.ChannelID)
	return err
}

const getAverageRatingForChannel = `-- name: GetAverageRatingForChannel :one
SELECT COALESCE(AVG(rating::float), 0) as avg_rating, COUNT(*) as rating_count
FROM ratings WHERE channel_id = $1
`

type GetAverageRatingForChannelRow struct {
	AvgRating   interface{} `json:"avg_rating"`
	RatingCount int64       `json:"rating_count"`
}

func (q *Queries) GetAverageRatingForChannel(ctx context.Context, channelID int64) (GetAverageRatingForChannelRow, error) {
	row := q.db.QueryRow(ctx, getAverageRatingForChannel, channelID)
	var i GetAverageRatingForChannelRow
	err := row.Scan(&i.AvgRating, &i.RatingCount)
	return i, err
}

const getRating = `-- name: GetRating :one
SELECT id, user_id, channel_id, rating, created_at, updated_at FROM ratings WHERE user_id = $1 AND channel_id = $2
`

type GetRatingParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getRating, arg.UserID, arg.ChannelID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (user_id, channel_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel_id) DO UPDATE SET
    rating = EXCLUDED.rating,
    updated_at = NOW()
RETURNING id, user_id, channel_id, rating, created_at, updated_at
`

type UpsertRatingParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
	Rating    int16 `json:"rating"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating, arg.UserID, arg.ChannelID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
