// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const globalSearch = `-- name: GlobalSearch :many
SELECT
    'channel' as result_type,
    c.id as result_id,
    c.name as result_name,
    c.avatar as result_avatar,
    c.handle as result_handle,
    c.description as result_description,
    c.subscriber_count as result_subscriber_count
FROM channels c
JOIN subscriptions s ON s.channel_id = c.id
WHERE s.user_id = $1
  AND (c.name ILIKE '%' || $2 || '%'
    OR c.handle ILIKE '%' || $2 || '%'
    OR c.description ILIKE '%' || $2 || '%')
UNION ALL
SELECT
    'collection' as result_type,
    cl.id as result_id,
    cl.name as result_name,
    '' as result_avatar,
    '' as result_handle,
    '' as result_description,
    0 as result_subscriber_count
FROM collections cl
WHERE cl.user_id = $1 AND cl.name ILIKE '%' || $2 || '%'
UNION ALL
SELECT
    'note' as result_type,
    n.channel_id as result_id,
    c.name as result_name,
    c.avatar as result_avatar,
    c.handle as result_handle,
    n.body as result_description,
    c.subscriber_count as result_subscriber_count
FROM notes n
JOIN channels c ON c.id = n.channel_id
WHERE n.user_id = $1 AND n.body ILIKE '%' || $2 || '%'
ORDER BY result_name ASC
LIMIT $3
`

type GlobalSearchParams struct {
	UserID  int64       `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
	Limit   int32       `json:"limit"`
}

type GlobalSearchRow struct {
	ResultType            string `json:"result_type"`
	ResultID              int64  `json:"result_id"`
	ResultName            string `json:"result_name"`
	ResultAvatar          string `json:"result_avatar"`
	ResultHandle          string `json:"result_handle"`
	ResultDescription     string `json:"result_description"`
	ResultSubscriberCount int64  `json:"result_subscriber_count"`
}

func (q *Queries) GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error) {
	rows, err := q.db.Query(ctx, globalSearch, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchRow{}
	for rows.Next() {
		var i GlobalSearchRow
		if err := rows.Scan(
			&i.ResultType,
			&i.ResultID,
			&i.ResultName,
			&i.ResultAvatar,
			&i.ResultHandle,
			&i.ResultDescription,
			&i.ResultSubscriberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
