// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubscriptionsByUser = `-- name: CountSubscriptionsByUser :one
SELECT COUNT(*) FROM subscriptions WHERE user_id = $1
`

func (q *Queries) CountSubscriptionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE user_id = $1 AND channel_id = $2
`

type DeleteSubscriptionParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.UserID, arg.ChannelID)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT s.id, s.user_id, s.channel_id, s.subscribed_at, s.synced_at, c.id as channel_id, c.name as channel_name, c.handle as channel_handle,
       c.avatar as channel_avatar, c.subscriber_count as channel_subscriber_count,
       c.description as channel_description, c.uploads_playlist_id,
       c.banner as channel_banner, c.youtube_channel_id
FROM subscriptions s
JOIN channels c ON c.id = s.channel_id
WHERE s.user_id = $1 AND s.channel_id = $2
`

type GetSubscriptionParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

type GetSubscriptionRow struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	ChannelID              int64              `json:"channel_id"`
	SubscribedAt           pgtype.Timestamptz `json:"subscribed_at"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	ChannelID_2            int64              `json:"channel_id_2"`
	ChannelName            string             `json:"channel_name"`
	ChannelHandle          string             `json:"channel_handle"`
	ChannelAvatar          string             `json:"channel_avatar"`
	ChannelSubscriberCount int64              `json:"channel_subscriber_count"`
	ChannelDescription     string             `json:"channel_description"`
	UploadsPlaylistID      string             `json:"uploads_playlist_id"`
	ChannelBanner          string             `json:"channel_banner"`
	YoutubeChannelID       string             `json:"youtube_channel_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.UserID, arg.ChannelID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.SubscribedAt,
		&i.SyncedAt,
		&i.ChannelID_2,
		&i.ChannelName,
		&i.ChannelHandle,
		&i.ChannelAvatar,
		&i.ChannelSubscriberCount,
		&i.ChannelDescription,
		&i.UploadsPlaylistID,
		&i.ChannelBanner,
		&i.YoutubeChannelID,
	)
	return i, err
}

const listSubscriptionChannelsByUser = `-- name: ListSubscriptionChannelsByUser :many
SELECT c.id, c.youtube_channel_id, c.name, c.handle, c.description, c.avatar, c.banner, c.subscriber_count, c.uploads_playlist_id, c.created_at, c.updated_at FROM channels c
JOIN subscriptions s ON s.channel_id = c.id
WHERE s.user_id = $1
`

func (q *Queries) ListSubscriptionChannelsByUser(ctx context.Context, userID int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listSubscriptionChannelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeChannelID,
			&i.Name,
			&i.Handle,
			&i.Description,
			&i.Avatar,
			&i.Banner,
			&i.SubscriberCount,
			&i.UploadsPlaylistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByName = `-- name: ListSubscriptionsByName :many
SELECT s.id, s.user_id, s.channel_id, s.subscribed_at, s.synced_at, c.id as channel_id, c.name as channel_name, c.handle as channel_handle,
       c.avatar as channel_avatar, c.subscriber_count as channel_subscriber_count,
       c.description as channel_description, c.uploads_playlist_id,
       c.banner as channel_banner, c.youtube_channel_id
FROM subscriptions s
JOIN channels c ON c.id = s.channel_id
WHERE s.user_id = $1
ORDER BY c.name ASC
LIMIT $2 OFFSET $3
`

type ListSubscriptionsByNameParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSubscriptionsByNameRow struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	ChannelID              int64              `json:"channel_id"`
	SubscribedAt           pgtype.Timestamptz `json:"subscribed_at"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	ChannelID_2            int64              `json:"channel_id_2"`
	ChannelName            string             `json:"channel_name"`
	ChannelHandle          string             `json:"channel_handle"`
	ChannelAvatar          string             `json:"channel_avatar"`
	ChannelSubscriberCount int64              `json:"channel_subscriber_count"`
	ChannelDescription     string             `json:"channel_description"`
	UploadsPlaylistID      string             `json:"uploads_playlist_id"`
	ChannelBanner          string             `json:"channel_banner"`
	YoutubeChannelID       string             `json:"youtube_channel_id"`
}

func (q *Queries) ListSubscriptionsByName(ctx context.Context, arg ListSubscriptionsByNameParams) ([]ListSubscriptionsByNameRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByName, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByNameRow{}
	for rows.Next() {
		var i ListSubscriptionsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.SubscribedAt,
			&i.SyncedAt,
			&i.ChannelID_2,
			&i.ChannelName,
			&i.ChannelHandle,
			&i.ChannelAvatar,
			&i.ChannelSubscriberCount,
			&i.ChannelDescription,
			&i.UploadsPlaylistID,
			&i.ChannelBanner,
			&i.YoutubeChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByRecent = `-- name: ListSubscriptionsByRecent :many
SELECT s.id, s.user_id, s.channel_id, s.subscribed_at, s.synced_at, c.id as channel_id, c.name as channel_name, c.handle as channel_handle,
       c.avatar as channel_avatar, c.subscriber_count as channel_subscriber_count,
       c.description as channel_description, c.uploads_playlist_id,
       c.banner as channel_banner, c.youtube_channel_id
FROM subscriptions s
JOIN channels c ON c.id = s.channel_id
WHERE s.user_id = $1
ORDER BY s.subscribed_at DESC
LIMIT $2 OFFSET $3
`

type ListSubscriptionsByRecentParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSubscriptionsByRecentRow struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	ChannelID              int64              `json:"channel_id"`
	SubscribedAt           pgtype.Timestamptz `json:"subscribed_at"`
	SyncedAt               pgtype.Timestamptz `json:"synced_at"`
	ChannelID_2            int64              `json:"channel_id_2"`
	ChannelName            string             `json:"channel_name"`
	ChannelHandle          string             `json:"channel_handle"`
	ChannelAvatar          string             `json:"channel_avatar"`
	ChannelSubscriberCount int64              `json:"channel_subscriber_count"`
	ChannelDescription     string             `json:"channel_description"`
	UploadsPlaylistID      string             `json:"uploads_playlist_id"`
	ChannelBanner          string             `json:"channel_banner"`
	YoutubeChannelID       string             `json:"youtube_channel_id"`
}

func (q *Queries) ListSubscriptionsByRecent(ctx context.Context, arg ListSubscriptionsByRecentParams) ([]ListSubscriptionsByRecentRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByRecent, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByRecentRow{}
	for rows.Next() {
		var i ListSubscriptionsByRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.SubscribedAt,
			&i.SyncedAt,
			&i.ChannelID_2,
			&i.ChannelName,
			&i.ChannelHandle,
			&i.ChannelAvatar,
			&i.ChannelSubscriberCount,
			&i.ChannelDescription,
			&i.UploadsPlaylistID,
			&i.ChannelBanner,
			&i.YoutubeChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (user_id, channel_id, subscribed_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel_id) DO UPDATE SET
    synced_at = NOW()
RETURNING id, user_id, channel_id, subscribed_at, synced_at
`

type UpsertSubscriptionParams struct {
	UserID       int64              `json:"user_id"`
	ChannelID    int64              `json:"channel_id"`
	SubscribedAt pgtype.Timestamptz `json:"subscribed_at"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription, arg.UserID, arg.ChannelID, arg.SubscribedAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.SubscribedAt,
		&i.SyncedAt,
	)
	return i, err
}
