// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_jobs.sql

package sqlc

import (
	"context"
)

const createSyncJob = `-- name: CreateSyncJob :one
INSERT INTO sync_jobs (user_id, status)
VALUES ($1, 'pending')
RETURNING id, user_id, started_at, finished_at, status, error
`

func (q *Queries) CreateSyncJob(ctx context.Context, userID int64) (SyncJob, error) {
	row := q.db.QueryRow(ctx, createSyncJob, userID)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getLatestSyncJob = `-- name: GetLatestSyncJob :one
SELECT id, user_id, started_at, finished_at, status, error FROM sync_jobs
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncJob(ctx context.Context, userID int64) (SyncJob, error) {
	row := q.db.QueryRow(ctx, getLatestSyncJob, userID)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const listSyncJobsByUser = `-- name: ListSyncJobsByUser :many
SELECT id, user_id, started_at, finished_at, status, error FROM sync_jobs
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListSyncJobsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSyncJobsByUser(ctx context.Context, arg ListSyncJobsByUserParams) ([]SyncJob, error) {
	rows, err := q.db.Query(ctx, listSyncJobsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncJob{}
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncJobStatus = `-- name: UpdateSyncJobStatus :exec
UPDATE sync_jobs
SET status = $2, finished_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE NULL END, error = $3
WHERE id = $1
`

type UpdateSyncJobStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
	Error  string `json:"error"`
}

func (q *Queries) UpdateSyncJobStatus(ctx context.Context, arg UpdateSyncJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateSyncJobStatus, arg.ID, arg.Status, arg.Error)
	return err
}
