// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestVideoByChannelID = `-- name: GetLatestVideoByChannelID :one
SELECT id, youtube_video_id, channel_id, title, description, published_at, thumbnail, created_at FROM videos
WHERE channel_id = $1
ORDER BY published_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVideoByChannelID(ctx context.Context, channelID int64) (Video, error) {
	row := q.db.QueryRow(ctx, getLatestVideoByChannelID, channelID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.YoutubeVideoID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Thumbnail,
		&i.CreatedAt,
	)
	return i, err
}

const getVideoByYouTubeID = `-- name: GetVideoByYouTubeID :one
SELECT id, youtube_video_id, channel_id, title, description, published_at, thumbnail, created_at FROM videos WHERE youtube_video_id = $1
`

func (q *Queries) GetVideoByYouTubeID(ctx context.Context, youtubeVideoID string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByYouTubeID, youtubeVideoID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.YoutubeVideoID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Thumbnail,
		&i.CreatedAt,
	)
	return i, err
}

const listVideosByChannelID = `-- name: ListVideosByChannelID :many
SELECT id, youtube_video_id, channel_id, title, description, published_at, thumbnail, created_at FROM videos
WHERE channel_id = $1
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListVideosByChannelIDParams struct {
	ChannelID int64 `json:"channel_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListVideosByChannelID(ctx context.Context, arg ListVideosByChannelIDParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByChannelID, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.YoutubeVideoID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Thumbnail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideo = `-- name: UpsertVideo :one
INSERT INTO videos (youtube_video_id, channel_id, title, description, published_at, thumbnail)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (youtube_video_id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    thumbnail = EXCLUDED.thumbnail
RETURNING id, youtube_video_id, channel_id, title, description, published_at, thumbnail, created_at
`

type UpsertVideoParams struct {
	YoutubeVideoID string             `json:"youtube_video_id"`
	ChannelID      int64              `json:"channel_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Thumbnail      string             `json:"thumbnail"`
}

func (q *Queries) UpsertVideo(ctx context.Context, arg UpsertVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, upsertVideo,
		arg.YoutubeVideoID,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Thumbnail,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.YoutubeVideoID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Thumbnail,
		&i.CreatedAt,
	)
	return i, err
}
